name: Continuous Deploy

on:
  push:
    branches: [ main ]
    
jobs:
  build-and-deploy:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          bun install

      - name: Build
        run: |
          bun build src/server.ts --compile --outfile server

      - name: Stop service
        run: |
          pm2 delete translate-server || true

      - name: Copy server to deploy folder
        run: |
          rm /home/ubuntu/codebase/translate-server/server
          cp server /home/ubuntu/codebase/translate-server/server

      - name: Start service
        run: |
          pm2 start /home/ubuntu/codebase/translate-server/server --cwd /home/ubuntu/codebase/translate-server --name translate-server
